---
- name: Ansible rancher server setup playbook
  gather_facts: false
  hosts: _RancherServer
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/etokral/.ssh/id_rsa.pub"
  tasks:
    - name: Install docker from rancher site
      shell: "curl https://releases.rancher.com/install-docker/20.10.sh | sh"
    - name: Install docker from rancher site
      shell: "docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher"
      become: true
